# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yhgBmNzZmpNe148D8KwiAstccXFSTAit
"""

pip install -r requirements.txt