# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10BRlwo3EMixVO4i1LHk2oksP33HSWUT9
"""

import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')